Add support for webp emotes
Xithrius/twitch-tui pull request #335
Opened 2023-04-13 09:44 UTC by Nogesma

Added support for 7tv zero-width emotes, which are basically just emote overlays.

Switched to `serde_json` instead of `json`. I didn't realize the `json` crate was unmaintained. I'm not really familiar with using serde so there might me a better way to define the structs in `downloader.rs`.

I found a way to avoid the code path in `image` that was causing a panic, so webp emotes should now work.

I have a PR in progress (image-rs/image#1907) that fixes an issue with emotes having a white background, so for now I switched the `image` version to point to my fixed fork. It is probably best to wait for it to get merged and a new version to be released before merging this.

2023-04-18 00:13 UTC, Xithrius requested changes
There seems to be a crash occurring at https://github.com/Nogesma/twitch-tui/blob/main/src/emotes/mod.rs#L149.

After removing the cache at `~/.cache/twt`, I believe that the app is trying to get emotes that haven't been downloaded yet.

Here's the solution I've come up with:

```rs
let info;

if let Some(emotes_info) = emotes.info.get(&emote.name) {
    info = emotes_info;
} else {
    return;
}
```

2023-04-18 02:17 UTC, Xithrius commented
This will close #341 as well.

2023-04-18 10:52 UTC, Nogesma commented
It's weird because there should never be emotes in `message_emotes` which are not in `emotes.info`. When I find a new emote in a message, I basically add it to `emotes.info` before even adding it to the message. 
https://github.com/Nogesma/twitch-tui/blob/0e69b4fdbb202bbe357882c6c7e5f97b0521f4f2/src/handlers/data.rs#L242 (`load_emote` adds the emote into `emotes.info`)

 I haven't managed to replicate it yet on my computer. I will add a log message if this happens so I can investigate.

2023-04-19 23:35 UTC, Xithrius approved these changes
Very nice. During this review, I detected no issues. The previous crash has been solved, according to my machine.

2023-04-20 03:00 UTC, merged

2023-04-20 07:57 UTC, Nogesma commented
Okay nice, I'll make another PR when image-rs will have a new release with the patch I have on my fork. 

I you find a way to reliably trigger the warning here: https://github.com/Xithrius/twitch-tui/blob/30e533e371dc964da0430033e299b245095b6d55/src/emotes/mod.rs#L152 please let me know, I think it's just a quick fix and the underlying issue is not fixed.

2023-04-21 21:31 UTC, Xithrius commented
It seems a new release of this crate won't be able to go through until your patch goes through on `image-rs`, given the following error on `cargo publish`:

```
error: all dependencies must have a version specified when publishing.
dependency `image` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
```

2023-04-21 23:03 UTC, Nogesma commented
Hmm, I can set it to the 0.24.6 version in the meantime, but most of 7tv emotes will have a white background.

2023-04-21 23:38 UTC, Xithrius commented
that'll do for now

2023-04-22 04:48 UTC, Xithrius commented
I'll just revert to that version until the fix happens

2023-04-22 05:11 UTC, Xithrius commented
reverted in a19dee51bb1dd296399c5a07781301a44e04272a