Add clap
Xithrius/twitch-tui pull request #58
Opened 2021-11-28 22:19 UTC by balroggg

Add parsing cli arguments by `clap` crate.

Add parsing some vars from config:
- twitch channel
- tick delay
- max messages
- date shown
- maximum username length
- username alignment
- palette

Example:
```
Running `target/debug/twt -h`
twitch-tui 1.4.1
Xithrius
Twitch chat in the terminal.

USAGE:
    twt [OPTIONS]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -c, --channel <CHANNEL>                         The streamer's name
    -s, --date-shown <true/false>                   If the time and date is to be shown
    -m, --max-messages <MESSAGES>                   The maximum amount of messages to be stored
    -u, --maximum-username-length <LENGTH>          The longest a username can be
    -p, --palette <PALETTE>
            The color palette for the username column: pastel (default), vibrant, warm, cool

    -t, --tick-delay <DELAY>                        The delay in milliseconds between terminal updates
    -a, --username-alignment <left/center/right>    Side the username should be aligned to
```

Fix issue with text alignment. Now column with `Username` crop without error(maybe add some minimal value of crop, length of string `Username` or max value of any username in chat).

Rewrite of [#57](https://github.com/Xithrius/twitch-tui/pull/57)

2021-11-28 22:42 UTC, Xithrius commented
I'll be reviewing this soon. I've closed the other CLI parsing PR.

2021-11-28 22:58 UTC, balroggg commented
Fix test `test_text_align_center`. Please check if I break logic, I try to use more core rust features.

2021-11-28 23:02 UTC, balroggg commented
> I'll be reviewing this soon. I've closed the other CLI parsing PR.

Ok, thanks.

2021-11-29 00:07 UTC, Xithrius requested changes

2021-11-29 00:07 UTC, Xithrius commented on src/main.rs
> +                          -s, --date-shown=[true/false] 'If the time and date is to be shown'
```suggestion
                          -s, --date-shown=[true/false] 'If the time and date is to be shown (defaults to true)'
```

2021-11-29 00:07 UTC, Xithrius commented on src/main.rs
> +            // twitch section of config
```suggestion
            // Twitch section of the config
```

2021-11-29 00:07 UTC, Xithrius commented on src/main.rs
> +            // terminal section of config
```suggestion
            // Terminal section of the config
```

2021-11-29 00:07 UTC, Xithrius commented on src/main.rs
> +            // frontend section of config
```suggestion
            // Frontend section of the config
```

2021-11-29 00:07 UTC, Xithrius commented on src/main.rs
> +                          -u, --maximum-username-length=[LENGTH] 'The longest a username can be'
```suggestion
                          -u, --maximum-username-length=[LENGTH] 'Maximum length for Twitch usernames'
```

2021-11-29 00:07 UTC, Xithrius commented on src/main.rs
> +
This isn't needed.
```suggestion
```

2021-11-29 18:29 UTC, balroggg commented
Fix typo and format code in utils

2021-12-02 10:48 UTC, Xithrius requested changes
Just want the user to type less. I'll change the config vars later to match. 

Besides these things, everything else looks good.

After this, the PR shall be merged.

2021-12-02 10:48 UTC, Xithrius commented on src/main.rs
> +                          -u, --maximum-username-length=[LENGTH] 'Maximum length for Twitch usernames'
```suggestion
                          -u, --max-username-length=[LENGTH] 'Maximum length for Twitch usernames'
```

2021-12-02 10:48 UTC, Xithrius commented on src/main.rs
> +            if let Some(max_messages) = arg_matches.value_of("maximum-messages") {
```suggestion
            if let Some(max_messages) = arg_matches.value_of("max-messages") {
```

2021-12-02 10:48 UTC, Xithrius commented on src/main.rs
> +            if let Some(maximum_username_length) = arg_matches.value_of("maximum-username-length") {
```suggestion
            if let Some(max_username_length) = arg_matches.value_of("max-username-length") {
```

2021-12-02 15:10 UTC, balroggg commented
> Just want the user to type less. I'll change the config vars later to match.
> 
> Besides these things, everything else looks good.
> 
> After this, the PR shall be merged.

Ok, good point.

2021-12-02 22:23 UTC, Xithrius approved these changes
Looks good. Thanks for the PR!

2021-12-02 22:24 UTC, merged

2021-12-02 22:45 UTC, Xithrius commented
@balroggg I'll be releasing a new version of the TUI relatively soon, just got to do a few things and then we'll be good to go.